// Para testes locais
spring.application.name=remi-central
spring.datasource.url=jdbc:postgresql://localhost:5432/remi-centraldb
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=FmiejAaxWKj0n883UFSrroCao5aZ81ZEqIe7IzLaJTtNKISnj_ET-Ll4Az93mobl_bOMsQUkQYnh7pOkbgPHLQ
jwt.expiration-ms=864000000
