# To local run

# DB credentials
spring.application.name=remi-central
spring.datasource.url=jdbc:postgresql://localhost:5432/remi-centraldb
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Application variables
jwt.secret=your-jwt-hash
jwt.expiration-ms=864000000
app.admin.password=your-password
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB

# Hibernate variables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Log variables (optional)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.apache.tomcat.util.http.fileupload=TRACE
logging.level.org.springframework.web.multipart=DEBUG
logging.level.org.springframework.web=DEBUG