# To local run
spring.application.name=remi-node
spring.datasource.url=jdbc:postgresql://localhost:5432/remi-nodedb
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional variables
node.auth.key=your-password
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.apache.tomcat.util.http.fileupload=TRACE
logging.level.org.springframework.web.multipart=DEBUG
logging.level.org.springframework.web=DEBUG