# To local run

# DB Credentials
spring.application.name=remi-node
spring.datasource.url=jdbc:sqlite:remi_node.db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.sqlite.JDBC

# Application variables
node.auth.key=your-password
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB
spring.threads.virtual.enabled=true

# Hibernate variables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Log variables
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.apache.tomcat.util.http.fileupload=TRACE
logging.level.org.springframework.web.multipart=DEBUG
logging.level.org.springframework.web=DEBUG