services:
  node:
    build:
      context: .
    container_name: remi-node
    depends_on:
      nodedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nodedb:5432/remi-nodedb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      NODE_AUTH_KEY: minha-senha-boa
    ports:
      - "8081:8080"
    volumes:
      - node_storage:/storage

  nodedb:
    image: postgres:16
    container_name: remi-nodedb
    environment:
      POSTGRES_DB: remi-nodedb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - nodedb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d remi-nodedb" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  nodedb_data:
  node_storage:
