name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  central-test:
    name: central
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./central
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "oracle"
          cache: maven
      - run: ./mvnw test -pl .
